### ISSUE TITLE
Replace 'compile' with 'implementation' and 'api'

### ISSUE THREAD

**Issue by mukarramali** [worker8/RadioGroupPlus#8]
Warning: `Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
Comes up everytime we build. Please make the small change.

**Comment by hendrawd** [comment]
You can also create a pull request since it is a simple task

**Comment by mukarramali** [comment]
https://github.com/worker8/RadioGroupPlus/pull/9

While I was updating it, I had to update other things as well. I hope it won't be a problem.
